version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.litebridgedb.example:*" # Ignore example projects
      - dependency-name: "org.litebridgedb.spring:litebridge-spring-boot3-test" # Ignore SB3 compatibility test
