version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    exclude-paths:
      - "example/litebridge-example-spring-boot3" # Ignore SB3 compatibility example app
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.litebridgedb.example:*" # Ignore example projects
      - dependency-name: "org.litebridgedb.spring:litebridge-spring-boot3-test" # Ignore SB3 compatibility test
