CREATE TABLE LB."GROUP"
(
    GROUP_NAME VARCHAR2(50)  NOT NULL PRIMARY KEY,
    GROUP_DESC VARCHAR2(255) NOT NULL
);

CREATE TABLE LB.PERSON_GROUP
(
    PERSON_ID  NUMBER(10)   NOT NULL REFERENCES LB.PERSON (PERSON_ID),
    GROUP_NAME VARCHAR2(50) NOT NULL REFERENCES LB."GROUP" (GROUP_NAME),

    PRIMARY KEY (PERSON_ID, GROUP_NAME)
);