CREATE TABLE LB.TENANT_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(255),
    SETTING_ID NUMBER(10)
);

CREATE TABLE LB.TENANT_SETTING_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    SETTING_KEY VARCHAR2(255),
    SETTING_VALUE VARCHAR2(255)
);

CREATE TABLE LB.ACCOUNT_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    TENANT_ID NUMBER(10),
    NAME VARCHAR2(255),
    SETTING_ID NUMBER(10)
);

CREATE TABLE LB.ACCOUNT_SETTING_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    SETTING_KEY VARCHAR2(255),
    SETTING_VALUE VARCHAR2(255)
);
