INSERT INTO LB.PERSON (PERSON_ID, FIRST_NAME, SURNAME, AGE) VALUES (NEXT VALUE FOR LB.PERSON_SEQ, 'John', 'Doe', 30);
--INSERT INTO LB.PERSON (PERSON_ID, FIRST_NAME, SURNAME, AGE) VALUES (2, 'Jane', 'Doe', 25);
--INSERT INTO LB.PERSON (PERSON_ID, FIRST_NAME, SURNAME, AGE) VALUES (3, 'Bob', 'Smith', 45);