CREATE TABLE "GROUP"
(
    GROUP_NAME TEXT NOT NULL PRIMARY KEY,
    GROUP_DESC TEXT NOT NULL
);

CREATE TABLE PERSON_GROUP
(
    PERSON_ID  INTEGER NOT NULL REFERENCES PERSON (PERSON_ID),
    GROUP_NAME TEXT    NOT NULL REFERENCES "GROUP" (GROUP_NAME),

    PRIMARY KEY (PERSON_ID, GROUP_NAME)
);
