CREATE TABLE COMP_PK_LOOKUP
(
    LOOKUP_ID   INTEGER NOT NULL PRIMARY KEY,
    LOOKUP_NAME TEXT NOT NULL
);

CREATE TABLE COMP_PK_FK_TEST
(
    LOOKUP_ID INTEGER NOT NULL REFERENCES COMP_PK_LOOKUP (LOOKUP_ID),
    TEST_ID   INTEGER NOT NULL,
    TEST_DESC TEXT,

    PRIMARY KEY (LOOKUP_ID, TEST_ID)
);

CREATE TABLE COMP_PK_SIMPLE
(
    PK1 INTEGER NOT NULL,
    PK2 INTEGER NOT NULL,
    TEST_DESC TEXT,

    PRIMARY KEY (PK1, PK2)
);
