CREATE TABLE TENANT_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    NAME TEXT,
    SETTING_ID NUMBER(10)
);

CREATE TABLE TENANT_SETTING_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    SETTING_KEY TEXT,
    SETTING_VALUE TEXT
);

CREATE TABLE ACCOUNT_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    TENANT_ID NUMBER(10),
    NAME TEXT,
    SETTING_ID NUMBER(10)
);

CREATE TABLE ACCOUNT_SETTING_A
(
    ID NUMBER(10) NOT NULL PRIMARY KEY,
    SETTING_KEY TEXT,
    SETTING_VALUE TEXT
);
