CREATE TABLE COMP_PK_LOOKUP
(
    LOOKUP_ID   INTEGER NOT NULL PRIMARY KEY,
    LOOKUP_NAME TEXT NOT NULL
);

CREATE TABLE COMP_PK_FK_TEST
(
    LOOKUP_ID INTEGER NOT NULL REFERENCES COMP_PK_LOOKUP (LOOKUP_ID),
    TEST_ID   INTEGER NOT NULL,
    TEST_DESC TEXT,

    PRIMARY KEY (LOOKUP_ID, TEST_ID)
);

CREATE TABLE COMP_PK_SIMPLE
(
    PK1 INTEGER NOT NULL,
    PK2 INTEGER NOT NULL,
    TEST_DESC TEXT,

    PRIMARY KEY (PK1, PK2)
);

CREATE TABLE COMP_PK_CHILD
(
    PK1        INTEGER NOT NULL,
    PK2        INTEGER NOT NULL,
    PARENT_PK1 INTEGER NOT NULL,
    PARENT_PK2 INTEGER NOT NULL,
    CHILD_DESC TEXT,

    PRIMARY KEY (PK1, PK2),

    FOREIGN KEY (PARENT_PK1, PARENT_PK2)
        REFERENCES COMP_PK_SIMPLE (PK1, PK2)
);

CREATE TABLE COMP_JOIN_TABLE
(
    LEFT_PK1  INTEGER NOT NULL,
    LEFT_PK2  INTEGER NOT NULL,
    RIGHT_PK1 INTEGER NOT NULL,
    RIGHT_PK2 INTEGER NOT NULL,

    PRIMARY KEY (LEFT_PK1, LEFT_PK2, RIGHT_PK1, RIGHT_PK2)
);
