-- Status associated with an application instance
CREATE TABLE APPLICATION_STATUS
(
    CODE INTEGER NOT NULL PRIMARY KEY,
    MESSAGE TEXT
);

-- Application instance
CREATE TABLE APPLICATION
(
    NAME TEXT NOT NULL PRIMARY KEY,
    STATUS_CODE INTEGER REFERENCES APPLICATION_STATUS(CODE)
);

-- Status associated with a server instance
CREATE TABLE SERVER_STATUS
(
    STATUS_CODE INTEGER NOT NULL PRIMARY KEY,
    MESSAGE TEXT
);

-- Server instance
CREATE TABLE SERVER
(
    HOST TEXT NOT NULL PRIMARY KEY,
    SERVER_STATUS_CODE INTEGER REFERENCES SERVER_STATUS(STATUS_CODE)
);
