<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.litebridgedb.example</groupId>
        <artifactId>litebridge-example</artifactId>
        <version>0.4.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>litebridge-example-oracle</artifactId>

    <name>Oracle Example</name>
    <description>Example application using the Oracle database provider for Litebridge</description>

    <build>
        <!-- Exclude from mvn install/deploy -->
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Project dependencies -->
        <dependency>
            <groupId>org.litebridgedb</groupId>
            <artifactId>litebridge-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-oracle</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.example</groupId>
            <artifactId>litebridge-example-common</artifactId>
        </dependency>

        <!-- External dependencies -->
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-oracle</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc17</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>
    </dependencies>

</project>