CREATE TABLE lb.e0
(
    id  NUMERIC(10) NOT NULL PRIMARY KEY,
    val VARCHAR(50) NOT NULL
);

CREATE TABLE lb.e1
(
    id    NUMERIC(10) NOT NULL PRIMARY KEY,
    val   VARCHAR(50) NOT NULL,
    e0_id NUMERIC(10) NOT NULL REFERENCES lb.e0 (id)
);

CREATE TABLE lb.e2
(
    id    NUMERIC(10) NOT NULL PRIMARY KEY,
    val   VARCHAR(50) NOT NULL,
    e1_id NUMERIC(10) NOT NULL REFERENCES lb.e1 (id)
);

CREATE TABLE lb.e3
(
    id    NUMERIC(10) NOT NULL PRIMARY KEY,
    val   VARCHAR(50) NOT NULL,
    e2_id NUMERIC(10) NOT NULL REFERENCES lb.e2 (id),
    e4_id NUMERIC(10) NOT NULL
);

CREATE TABLE lb.e4
(
    id    NUMERIC(10) NOT NULL PRIMARY KEY,
    val   VARCHAR(50) NOT NULL,
    e5_id NUMERIC(10) NOT NULL
);

ALTER TABLE lb.e3
    ADD CONSTRAINT FK_e3_e4 FOREIGN KEY (e4_id) REFERENCES lb.e4 (id);

CREATE TABLE lb.e5
(
    id    NUMERIC(10) NOT NULL PRIMARY KEY,
    val   VARCHAR(50) NOT NULL,
    e4_id NUMERIC(10) NOT NULL REFERENCES lb.e4 (id)
);

ALTER TABLE lb.e4
    ADD CONSTRAINT FK_e4_e5 FOREIGN KEY (e5_id) REFERENCES lb.e5 (id);

CREATE TABLE lb.e6
(
    id  NUMERIC(10) NOT NULL PRIMARY KEY,
    val VARCHAR(50) NOT NULL
);

CREATE TABLE lb.e7
(
    id    NUMERIC(10) NOT NULL PRIMARY KEY,
    val   VARCHAR(50) NOT NULL,
    e6_id NUMERIC(10) NOT NULL REFERENCES lb.e6 (id)
);

CREATE TABLE lb.e8
(
    id  NUMERIC(10) NOT NULL PRIMARY KEY,
    val VARCHAR(50) NOT NULL
);

CREATE TABLE lb.e9
(
    id    NUMERIC(10) NOT NULL PRIMARY KEY,
    val   VARCHAR(50) NOT NULL,
    e8_id NUMERIC(10) NOT NULL REFERENCES lb.e8 (id)
);