CREATE TABLE LB.E0
(
    ID  NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL VARCHAR2(50) NOT NULL
);

CREATE TABLE LB.E1
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E0_ID NUMBER(10)   NOT NULL REFERENCES LB.E0 (ID)
);

CREATE TABLE LB.E2
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E1_ID NUMBER(10)   NOT NULL REFERENCES LB.E1 (ID)
);

CREATE TABLE LB.E3
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E2_ID NUMBER(10)   NOT NULL REFERENCES LB.E2 (ID),
    E4_ID NUMBER(10)   NOT NULL
);

CREATE TABLE LB.E4
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E5_ID NUMBER(10)   NOT NULL
);

ALTER TABLE LB.E3
    ADD CONSTRAINT FK_E3_E4 FOREIGN KEY (E4_ID) REFERENCES LB.E4 (ID);

CREATE TABLE LB.E5
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E4_ID NUMBER(10)   NOT NULL REFERENCES LB.E4 (ID)
);

ALTER TABLE LB.E4
    ADD CONSTRAINT FK_E4_E5 FOREIGN KEY (E5_ID) REFERENCES LB.E5 (ID);

CREATE TABLE LB.E6
(
    ID  NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL VARCHAR2(50) NOT NULL
);

CREATE TABLE LB.E7
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E6_ID NUMBER(10)   NOT NULL REFERENCES LB.E6 (ID)
);

CREATE TABLE LB.E8
(
    ID  NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL VARCHAR2(50) NOT NULL
);

CREATE TABLE LB.E9
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E8_ID NUMBER(10)   NOT NULL REFERENCES LB.E8 (ID)
);