INSERT INTO LB.PERSON (PERSON_ID, FIRST_NAME, SURNAME, AGE) VALUES (1, 'John', 'Doe', 30);
INSERT INTO LB.PERSON (PERSON_ID, FIRST_NAME, SURNAME, AGE) VALUES (2, 'Jane', 'Doe', 25);
INSERT INTO LB.PERSON (PERSON_ID, FIRST_NAME, SURNAME, AGE) VALUES (3, 'Bob', 'Smith', 45);