CREATE SEQUENCE LB.PERSON_SEQ START WITH 1 MAXVALUE 999 INCREMENT BY 1;
CREATE SEQUENCE LB.ACCOUNT_SEQ START WITH 1 MAXVALUE 999 INCREMENT BY 1;

CREATE TABLE LB.PERSON
(
    PERSON_ID  NUMBER(10)    NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR2(255) NOT NULL,
    SURNAME    VARCHAR2(255),
    AGE        NUMBER(3),
    EYE_COLOUR VARCHAR2(255)
);

CREATE TABLE LB.ACCOUNT
(
    ACCOUNT_ID   NUMBER(10)    NOT NULL PRIMARY KEY,
    ACCOUNT_NAME VARCHAR2(255) NOT NULL,
    BALANCE      NUMBER(10)    NOT NULL,
    PERSON_ID    NUMBER(10)    NOT NULL REFERENCES LB.PERSON (PERSON_ID)
);