CREATE TABLE LB.COMP_PK_LOOKUP
(
    LOOKUP_ID   NUMBER(10)   NOT NULL PRIMARY KEY,
    LOOKUP_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE LB.COMP_PK_FK_TEST
(
    LOOKUP_ID NUMBER(10) NOT NULL REFERENCES LB.COMP_PK_LOOKUP (LOOKUP_ID),
    TEST_ID   NUMBER(10) NOT NULL,
    TEST_DESC VARCHAR2(50),

    PRIMARY KEY (LOOKUP_ID, TEST_ID)
);


