CREATE SEQUENCE LB.COMPOSITE_PK1_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LB.COMPOSITE_PK2_SEQ START WITH 2 INCREMENT BY 1;

CREATE TABLE LB.COMP_PK_LOOKUP
(
    LOOKUP_ID   NUMBER(10)   NOT NULL PRIMARY KEY,
    LOOKUP_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE LB.COMP_PK_FK_TEST
(
    LOOKUP_ID NUMBER(10) NOT NULL REFERENCES LB.COMP_PK_LOOKUP (LOOKUP_ID),
    TEST_ID   NUMBER(10) NOT NULL,
    TEST_DESC VARCHAR2(50),

    PRIMARY KEY (LOOKUP_ID, TEST_ID)
);

CREATE TABLE LB.COMP_PK_SIMPLE
(
    PK1 NUMBER(10) NOT NULL,
    PK2 NUMBER(10) NOT NULL,
    TEST_DESC VARCHAR2(50),

    PRIMARY KEY (PK1, PK2)
);