CREATE TABLE LB.PERSON
(
    PERSON_ID  NUMBER(10)    NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR2(255) NOT NULL,
    SURNAME    VARCHAR2(255) NOT NULL,
    AGE        NUMBER(3)     NOT NULL,
    EYE_COLOUR VARCHAR2(255)
);

CREATE TABLE LB.ACCOUNT
(
    ACCOUNT_ID   NUMBER(10)    NOT NULL PRIMARY KEY,
    ACCOUNT_NAME VARCHAR2(255) NOT NULL,
    BALANCE      NUMBER(10)    NOT NULL,
    PERSON_ID    NUMBER(10)    NOT NULL REFERENCES LB.PERSON (PERSON_ID)
);

CREATE TABLE LB.ADDRESS
(
    ADDRESS_ID NUMBER(10)    NOT NULL PRIMARY KEY,
    STREET     VARCHAR2(255) NOT NULL,
    CITY       VARCHAR2(255) NOT NULL
);

CREATE TABLE LB.PERSON_ADDRESS
(
    PERSON_ID  NUMBER(10) NOT NULL REFERENCES LB.PERSON (PERSON_ID),
    ADDRESS_ID NUMBER(10) NOT NULL REFERENCES LB.ADDRESS (ADDRESS_ID),

    PRIMARY KEY (PERSON_ID, ADDRESS_ID)
);

CREATE TABLE LB.NESTED_DTO
(
    PARENT_VALUE1     VARCHAR2(255) PRIMARY KEY,
    CHILD_VALUE1      VARCHAR2(255),
    GRANDCHILD_VALUE1 VARCHAR2(255)
);

CREATE TABLE LB.SELF_REFERENCING
(
    ID        NUMBER(10) NOT NULL PRIMARY KEY,
    MY_VAR    VARCHAR2(255),
    PARENT_ID NUMBER(10) REFERENCES LB.SELF_REFERENCING (ID)
);