<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.litebridgedb</groupId>
        <artifactId>litebridge</artifactId>
        <version>0.2.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>litebridge-orm</artifactId>

    <name>Litebridge ORM</name>
    <description>Fast, lightweight Object-Relational Mapper (ORM) for Java 21+</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        @{argLine}
                        -javaagent:${org.mockito:mockito-core:jar}
                        --add-opens litebridge.orm/org.litebridgedb.orm=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.api.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.api.dto.delete=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.api.dto.update=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.api.select=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.api.select.impl=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.api.select.impl=ALL-UNNAMED
                        --add-opens litebridge.orm/org.litebridgedb.orm.persistence=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e=ALL-UNNAMED
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.setup=ALL-UNNAMED
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.basic.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.basic.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.compositepk.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.compositepk.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.manytomany.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.manytomany.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.selfref.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.selfref.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.shareddto.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.shareddto.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.singletable_multidto.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridgedb.orm.e2e.singletable_multidto.dto=litebridge.tracking
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Project dependencies -->
        <dependency>
            <groupId>org.litebridgedb</groupId>
            <artifactId>litebridge-converter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb</groupId>
            <artifactId>litebridge-tracking</artifactId>
        </dependency>

        <!-- External dependencies -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-oracle</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-sqlite</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-oracle</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc17</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-oracle-xe</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>