<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.litebridge</groupId>
        <artifactId>litebridge</artifactId>
        <version>0.0.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>litebridge-orm</artifactId>
    <version>0.0.1</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        @{argLine}
                        --add-opens litebridge.orm/org.litebridge.orm=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridge.orm.api.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.api.select=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridge.orm.api.select.impl=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.api.select.impl=ALL-UNNAMED
                        --add-opens litebridge.orm/org.litebridge.orm.persistence=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.basic.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.basic.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.manytomany.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.manytomany.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.selfref.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.selfref.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.shareddto.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.shareddto.dto=litebridge.tracking
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.singletable_multidto.dto=litebridge.commons
                        --add-opens litebridge.orm/org.litebridge.orm.e2e.singletable_multidto.dto=litebridge.tracking
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Project dependencies -->
        <dependency>
            <groupId>org.litebridge.db</groupId>
            <artifactId>litebridge-db-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridge</groupId>
            <artifactId>litebridge-tracking</artifactId>
        </dependency>

        <!-- External dependencies -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.litebridge.db</groupId>
            <artifactId>litebridge-db-h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>