package org.litebridge.db.spi.query;

import org.litebridge.db.spi.ColumnMetaData;

import java.util.List;

/**
 * Update operation metadata.
 *
 * @param returnGeneratedKeys a boolean indicating whether the statement should return generated keys.
 *                            Pass {@code true} to configure the statement to return generated keys,
 *                            or {@code false} otherwise.
 * @param generatedKeys       List of metadata for columns that are generated by the database.
 * @param generatedKeyNames   Array of column names that are generated by the database.
 */
public record UpdateMetaData(boolean returnGeneratedKeys,
                             List<ColumnMetaData> generatedKeys,
                             String[] generatedKeyNames) {
}
