CREATE TABLE LB.PERSON
(
    PERSON_ID  NUMBER(10) NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR2(255) NOT NULL,
    SURNAME    VARCHAR2(255) NOT NULL,
    AGE        NUMBER(3) NOT NULL,
    EYE_COLOUR VARCHAR2(255)
);

CREATE TABLE LB.ACCOUNT
(
    ACCOUNT_ID   NUMBER(10) NOT NULL PRIMARY KEY,
    ACCOUNT_NAME VARCHAR2(255) NOT NULL,
    PERSON_ID    NUMBER(10) NOT NULL REFERENCES LB.PERSON(PERSON_ID)
);