<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.litebridgedb</groupId>
        <artifactId>litebridge</artifactId>
        <version>0.3.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>org.litebridgedb.jacoco</groupId>
    <artifactId>jacoco-aggregate-report</artifactId>
    <packaging>pom</packaging>

    <name>Jacoco Aggregate Report</name>
    <description>Generates aggregate code coverage report for Litebridge</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                        <configuration>
                            <dataFileIncludes>
                                <dataFileInclude>**/jacoco.exec</dataFileInclude>
                            </dataFileIncludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Exclude from mvn install/deploy -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Project dependencies -->
        <dependency>
            <groupId>org.litebridgedb</groupId>
            <artifactId>litebridge-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb</groupId>
            <artifactId>litebridge-converter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-spi-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-h2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb</groupId>
            <artifactId>litebridge-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb</groupId>
            <artifactId>litebridge-tracking</artifactId>
        </dependency>
    </dependencies>
</project>