CREATE TABLE E0
(
    ID  NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL VARCHAR2(50) NOT NULL
);

CREATE TABLE E1
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E0_ID NUMBER(10)   NOT NULL REFERENCES E0 (ID)
);

CREATE TABLE E2
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E1_ID NUMBER(10)   NOT NULL REFERENCES E1 (ID)
);

CREATE TABLE E3
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E2_ID NUMBER(10)   NOT NULL REFERENCES E2 (ID),
    E4_ID NUMBER(10)   NOT NULL REFERENCES E4 (ID)
);

CREATE TABLE E4
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E5_ID NUMBER(10)   NOT NULL REFERENCES E5 (ID)
);

CREATE TABLE E5
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E4_ID NUMBER(10)   NOT NULL REFERENCES E4 (ID)
);

CREATE TABLE E6
(
    ID  NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL VARCHAR2(50) NOT NULL
);

CREATE TABLE E7
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E6_ID NUMBER(10)   NOT NULL REFERENCES E6 (ID)
);

CREATE TABLE E8
(
    ID  NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL VARCHAR2(50) NOT NULL
);

CREATE TABLE E9
(
    ID    NUMBER(10)   NOT NULL PRIMARY KEY,
    VAL   VARCHAR2(50) NOT NULL,
    E8_ID NUMBER(10)   NOT NULL REFERENCES E8 (ID)
);