CREATE TABLE PERSON
(
    PERSON_ID  INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME TEXT NOT NULL,
    SURNAME    TEXT,
    AGE        INTEGER,
    EYE_COLOUR TEXT
);

CREATE TABLE ACCOUNT
(
    ACCOUNT_ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_NAME TEXT NOT NULL,
    BALANCE      INTEGER NOT NULL,
    PERSON_ID    INTEGER NOT NULL REFERENCES PERSON (PERSON_ID)
);
