package org.litebridge.orm.persistence;

import org.litebridge.db.spi.update.UpdateResult;

import java.util.function.Consumer;

/**
 * A statement in the context of dependent database operations that is built using an
 * {@link AbstractStatementBuilder} and optionally pipes result values using a {@link Consumer}.
 * <p>
 * This class is intended to encapsulate the process of preparing and managing a dependency of another database
 * statement, associating an optional consumer for handling update results.
 * <p>
 * The class uses the following components:
 * - {@link AbstractStatementBuilder}: Responsible for building the database statement.
 * - {@link Consumer}: Handles the {@link UpdateResult} generated by executing the statement.
 * <p>
 * The primary constructor takes both a statement builder and a consumer for processing update
 * results. An additional constructor allows for creating an instance with a default no-op consumer.
 *
 * @param statementBuilder The statement builder to be used for building the dependency statement.
 * @param dto              The DTO associated with the statement.
 * @param valuePipe        The consumer for handling the {@link UpdateResult} generated by executing the statement.
 */
public record PipedStatement(StatementBuilder<?> statementBuilder, Object dto, Consumer<UpdateResult> valuePipe) {

    /**
     * Constructs a new {@code PipedStatement} using the given {@link AbstractStatementBuilder}.
     * <p>
     * This constructor creates a piped statement with a default no-op consumer for handling
     * update results.
     *
     * @param statementBuilder The statement builder to be used for building the dependency statement.
     */
    public PipedStatement(final StatementBuilder<?> statementBuilder, final Object dto) {
        this(statementBuilder, dto, updateResult -> {
        });
    }
}
