<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.litebridgedb.spring</groupId>
        <artifactId>litebridge-spring-parent</artifactId>
        <version>0.3.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>litebridge-spring-boot-autoconfigure</artifactId>

    <name>Litebridge Spring Boot Autoconfigure</name>
    <description>Spring Boot autoconfiguration library for Litebridge</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>@{argLine}
                        -javaagent:${org.mockito:mockito-core:jar}
                        --add-opens litebridge.spring.boot.autoconfigure/org.litebridgedb.spring.boot.autoconfigure.test.entity=spring.beans
                        --add-opens litebridge.spring.boot.autoconfigure/org.litebridgedb.spring.boot.autoconfigure.test.mapping=spring.beans
                        --add-opens litebridge.spring.boot.autoconfigure/org.litebridgedb.spring.boot.autoconfigure.test.mapping=litebridge.orm
                        --add-opens litebridge.spring.boot.autoconfigure/org.litebridgedb.spring.boot.autoconfigure.test.entity=litebridge.orm
                        --add-opens litebridge.orm/org.litebridgedb.orm=litebridge.spring.boot.autoconfigure
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <!-- Project dependencies -->
        <dependency>
            <groupId>org.litebridgedb.spring</groupId>
            <artifactId>litebridge-spring</artifactId>
        </dependency>

        <!-- External dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-sql</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.litebridgedb.db</groupId>
            <artifactId>litebridge-db-h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>