package org.litebridge.db.spi.sql;

import org.litebridge.db.spi.Operation;
import org.litebridge.db.spi.expression.LiteralExpression;
import org.litebridge.db.spi.expression.SelectExpression;
import org.litebridge.db.spi.expression.SubselectExpression;
import org.litebridge.db.spi.query.Condition;
import org.litebridge.db.spi.query.ConditionGroup;
import org.litebridge.db.spi.query.Join;
import org.litebridge.db.spi.query.LogicCondition;
import org.litebridge.db.spi.query.LogicConditionGroup;
import org.litebridge.db.spi.query.Operator;
import org.litebridge.db.spi.query.Select;
import org.litebridge.db.spi.sql.BindValue;

import java.util.ArrayList;
import java.util.List;

/**
 * Extracts bind parameters from a {@link Select} record in the same order
 * as they would be generated by {@link SelectSqlGenerator}.
 */
public final class ParameterExtractor {

    /**
     * Extracts bind parameters from the given {@link Select} operation.
     *
     * @param select the select operation
     * @return a list of bind values
     */
    public List<BindValue> extractParameters(final Select select) {
        final List<BindValue> bindValues = new ArrayList<>();

        // Joins
        for (final Join join : select.joins()) {
            extractFromConditionGroup(join.conditions(), bindValues, select);
        }

        // Where
        select.where().ifPresent(where -> extractFromConditionGroup(where, bindValues, select));

        // Group By
        // (Usually doesn't have literals, but let's check for consistency with SelectSqlGenerator)

        // Having
        select.having().ifPresent(having -> extractFromConditionGroup(having, bindValues, select));

        return bindValues;
    }

    private void extractFromConditionGroup(final ConditionGroup group, final List<BindValue> bindValues, final Operation operation) {
        for (final LogicCondition logicCondition : group.conditions()) {
            extractFromCondition(logicCondition.condition(), bindValues, operation);
        }
        for (final LogicConditionGroup logicGroup : group.subgroups()) {
            extractFromConditionGroup(logicGroup.conditionGroup(), bindValues, operation);
        }
    }

    private void extractFromCondition(final Condition condition, final List<BindValue> bindValues, final Operation operation) {
        final Operator op = condition.operator();
        final SelectExpression rhs = condition.rhs();

        if (op == Operator.IS_NULL || op == Operator.IS_NOT_NULL || op == Operator.USING) {
            return;
        }

        if (rhs instanceof LiteralExpression literalExpression) {
            final Object value = literalExpression.value();
            if (value instanceof java.util.Collection<?> collection) {
                for (Object item : collection) {
                    bindValues.add(new BindValue(item, 0));
                }
            } else {
                bindValues.add(new BindValue(value, 0));
            }
        } else if (rhs instanceof SubselectExpression subselectExpression) {
            bindValues.addAll(extractParameters(subselectExpression.select()));
        }
    }
}
