name: Maven build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven and generate JaCoCo report
      run: mvn -B clean verify

    - name: "Generate JaCoCo Badge: litebridgedb-commons"
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-commons/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-commons
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-converter"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-converter/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-converter
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-db-spi"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-db/litebridgedb-db-spi/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-db/litebridgedb-db-spi
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-db-spi-impl"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-db/litebridgedb-db-spi-impl/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-db/litebridgedb-db-spi-impl
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-db-h2"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-db/litebridgedb-db-h2/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-db/litebridgedb-db-h2
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-db-oracle"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-db/litebridgedb-db-oracle/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-db/litebridgedb-db-oracle
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-orm"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-orm/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-orm
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-tracking"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: litebridgedb-tracking/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/litebridgedb-tracking
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-spring"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: spring/litebridgedb-spring/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/spring/litebridgedb-spring
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: litebridgedb-spring-boot-autoconfigure"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: spring/litebridgedb-spring-boot-autoconfigure/target/site/jacoco/jacoco.csv
        badges-directory: .github/badges/spring/litebridgedb-spring-boot-autoconfigure
        generate-branches-badge: true

    - name: "Generate JaCoCo Badge: aggregate"
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: jacoco-aggregate-report/target/site/jacoco-aggregate/jacoco.csv
        generate-branches-badge: true
    
    - name: Log coverage percentage
      run: |
        echo "Coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "Branch coverage = ${{ steps.jacoco.outputs.branches }}"

    - name: Commit JaCoCo badge (if it changed)
      # Run on main branch only
      if: github.ref == 'refs/heads/main'
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Francois Aucamp'
          git config --global user.email 'faucamp@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v6
      with:
        name: jacoco-report
        path: jacoco-aggregate-report/target/site/jacoco-aggregate/
        
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
